apiVersion: v1
kind: Service
metadata:
  name: springlogmonitor
  labels:
    app: springlogmonitor
    service: springlogmonitor
spec:
  type: LoadBalancer	
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: springlogmonitor